definitions:
  image.FileItem:
    properties:
      name:
        description: 文件或目录名
        type: string
      path:
        description: 相对路径
        type: string
      type:
        description: file | dir
        type: string
      url:
        description: 文件访问 URL，仅 file 有
        type: string
    type: object
  image.ListFilesResp:
    properties:
      code:
        $ref: '#/definitions/response.Code'
      data:
        items:
          $ref: '#/definitions/image.FileItem'
        type: array
      msg:
        type: string
    type: object
  image.UploadResp:
    properties:
      code:
        $ref: '#/definitions/response.Code'
      msg:
        type: string
      url:
        type: string
    type: object
  response.Code:
    enum:
    - 200
    - 401
    - 500
    - 504
    type: integer
    x-enum-varnames:
    - Code_Success
    - Code_Unauthorized
    - Code_Err
    - Code_CaptchaErr
  response.CommonResp:
    properties:
      code:
        $ref: '#/definitions/response.Code'
      msg:
        type: string
    type: object
  user.CaptchaData:
    properties:
      base64_image:
        type: string
      id:
        type: string
    type: object
  user.CaptchaResp:
    properties:
      code:
        $ref: '#/definitions/response.Code'
      data:
        $ref: '#/definitions/user.CaptchaData'
      msg:
        type: string
    type: object
  user.TestTokenReq:
    properties:
      captcha:
        maxLength: 10
        minLength: 1
        type: string
      captcha_id:
        maxLength: 255
        minLength: 1
        type: string
      token:
        maxLength: 255
        minLength: 1
        type: string
    required:
    - captcha
    - captcha_id
    - token
    type: object
info:
  contact:
    name: buyfakett
    url: https://github.com/buyfakett
paths:
  /api/image/delete:
    delete:
      consumes:
      - application/json
      description: 删除相对图片目录下的文件
      parameters:
      - description: 文件路径
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResp'
      summary: 删除文件
      tags:
      - 图片
  /api/image/list:
    get:
      consumes:
      - application/json
      description: 获取指定目录下的文件与子目录（不递归）
      parameters:
      - description: 相对 图片 的目录，不传表示根目录
        in: query
        name: dir
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image.ListFilesResp'
      summary: 获取文件列表
      tags:
      - 图片
  /api/image/upload:
    put:
      consumes:
      - multipart/form-data
      description: 上传图片
      parameters:
      - description: 图片文件
        in: formData
        name: file
        required: true
        type: file
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/image.UploadResp'
      security:
      - ApiKeyAuth: []
      summary: 上传图片
      tags:
      - 图片
  /api/metrics:
    get:
      responses: {}
      summary: 普罗米修斯监控
      tags:
      - 监控
  /api/ping:
    get:
      consumes:
      - application/json
      description: 测试网络接口
      produces:
      - application/json
      responses: {}
      summary: 测试网络接口
      tags:
      - 测试
  /api/server_info:
    get:
      consumes:
      - application/json
      description: 服务信息
      produces:
      - application/json
      responses: {}
      summary: 服务信息
      tags:
      - 测试
  /api/user/captcha:
    get:
      description: 生成登录验证码
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CaptchaResp'
      summary: 生成验证码
      tags:
      - 用户
  /api/user/test_token:
    post:
      consumes:
      - application/json
      description: 测试token权限
      parameters:
      - description: 测试token权限
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/user.TestTokenReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CommonResp'
      summary: 测试token权限
      tags:
      - 测试
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: authorization
    type: apiKey
swagger: "2.0"
